default_model = "kimi-code/kimi-for-coding"
default_thinking = true

[providers."managed:kimi-code"]
type = "kimi"
api_key = ""
base_url = "https://api.kimi.com/coding/v1"

[providers."managed:kimi-code".oauth]
storage = "file"
key = "oauth/kimi-code"

[models."kimi-code/kimi-for-coding"]
provider = "managed:kimi-code"
model = "kimi-for-coding"
max_context_size = 262144
capabilities = [ "thinking", "image_in", "video_in", "tool_use" ]
display_name = "Kimi-k2.6"

[services.moonshot_search]
base_url = "https://api.kimi.com/coding/v1/search"
api_key = ""

[services.moonshot_search.oauth]
storage = "file"
key = "oauth/kimi-code"

[services.moonshot_fetch]
base_url = "https://api.kimi.com/coding/v1/fetch"
api_key = ""

[services.moonshot_fetch.oauth]
storage = "file"
key = "oauth/kimi-code"

[[plugins]]
path = "/data/data/com.termux/files/home/kimi-code/plugins/official/kimi-datasource"

[[plugins]]
path = "/data/data/com.termux/files/home/kimi-code/plugins/curated/superpowers"

[mcp_servers.filesystem]
command = "npx"
args = [ "-y", "@modelcontextprotocol/server-filesystem", "/data/data/com.termux/files/home" ]

[mcp_servers.git]
command = "npx"
args = [ "-y", "@modelcontextprotocol/server-git", "--repository", "/data/data/com.termux/files/home" ]

[mcp_servers.fetch]
command = "npx"
args = [ "-y", "@modelcontextprotocol/server-fetch" ]

[mcp_servers.sequential-thinking]
command = "npx"
args = [ "-y", "@modelcontextprotocol/server-sequential-thinking" ]

[mcp_servers.memory]
command = "npx"
args = [ "-y", "@modelcontextprotocol/server-memory" ]

[mcp_servers.everything]
command = "npx"
args = [ "-y", "@modelcontextprotocol/server-everything" ]

[mcp_servers.brave-search]
command = "npx"
args = [ "-y", "@modelcontextprotocol/server-brave-search" ]
skills_dirs = [ "/data/data/com.termux/files/home/kimi-code/.agents/skills", "/data/data/com.termux/files/home/kimi-cli/.agents/skills" ]

[mcp_servers.brave-search.env]
BRAVE_API_KEY = ""
